azure.openai.endpoint=https://freeeed-openai.openai.azure.com/
azure.openai.key=864281421ae44d7c98efb5723ef60599
azure.openai.api-version=2024-02-15-preview
azure.blob.connectionString=DefaultEndpointsProtocol=https;AccountName=testingforms;AccountKey=fERfGmgwBzYipf+6e2OlhRVO3dGuK9NuTYSt77Pq5cSBeFhTHWcSp8XyWkqLI0es07l155ecVxcB+AStrtxliQ==;EndpointSuffix=core.usgovcloudapi.net
azure.blob.inputcontainer=input
azure.blob.outputcontainer=output
azure.blob.downloadpath=/tmp
tika.url=http://localhost:9998/tika
question1=who is the main character
question2=summarise the document