azure.openai.endpoint=https://freeeed-openai.openai.azure.com/
azure.openai.key=864281421ae44d7c98efb5723ef60599
azure.openai.api-version=2024-02-15-preview
azure.blob.connectionString=DefaultEndpointsProtocol=https;AccountName=rap;AccountKey=5S1iyjCrE6d7IWrXASlNB4BMfYQxvZP5eV0yO3ujdCtReODmabKCzlzagwqnAkodrXaJh6OeouuJ+AStbpLEkg==;EndpointSuffix=core.usgovcloudapi.net
azure.blob.inputcontainer=rapinput
azure.blob.outputcontainer=rapoutput
azure.blob.downloadpath=/tmp
tika.url=http://localhost:9998/tika
question1=who is the main character
question2=summarise the document